// Mocks generated by Mockito 5.2.0 from annotations
// in sub1experttonton/test/presentation/bloc/unitvy_bloc/recomendation_unitvy_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i7;
import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sub1experttonton/common/failure.dart' as _i8;
import 'package:sub1experttonton/domain/entities/unitvy/unitvy.dart' as _i9;
import 'package:sub1experttonton/domain/repositories/unitvy_repository.dart'
    as _i4;
import 'package:sub1experttonton/domain/usecases/unitvy/get_unitvy_recomendations.dart'
    as _i2;
import 'package:sub1experttonton/presentation/bloc/unitvy_bloc/recommendation_unitvy_bloc/recommendation_unitvy_bloc.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetUnitvyRecommendations_0 extends _i1.Fake
    implements _i2.GetUnitvyRecommendations {}

class _FakeRecommendationUnitvyState_1 extends _i1.Fake
    implements _i3.RecommendationUnitvyState {}

class _FakeUnitvyRepository_2 extends _i1.Fake implements _i4.UnitvyRepository {
}

class _FakeEither_3<L, R> extends _i1.Fake implements _i5.Either<L, R> {}

/// A class which mocks [RecommendationUnitvyBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationUnitvyBloc extends _i1.Mock
    implements _i3.RecommendationUnitvyBloc {
  MockRecommendationUnitvyBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetUnitvyRecommendations get getUnitvyRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getUnitvyRecommendations),
              returnValue: _FakeGetUnitvyRecommendations_0())
          as _i2.GetUnitvyRecommendations);
  @override
  _i3.RecommendationUnitvyState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeRecommendationUnitvyState_1())
          as _i3.RecommendationUnitvyState);
  @override
  _i6.Stream<_i3.RecommendationUnitvyState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.RecommendationUnitvyState>.empty())
          as _i6.Stream<_i3.RecommendationUnitvyState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i3.RecommendationUnitvyEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.RecommendationUnitvyEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i3.RecommendationUnitvyState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i3.RecommendationUnitvyEvent>(
          _i7.EventHandler<E, _i3.RecommendationUnitvyState>? handler,
          {_i7.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i7.Transition<_i3.RecommendationUnitvyEvent,
                  _i3.RecommendationUnitvyState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void onChange(_i7.Change<_i3.RecommendationUnitvyState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetUnitvyRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUnitvyRecommendations extends _i1.Mock
    implements _i2.GetUnitvyRecommendations {
  MockGetUnitvyRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UnitvyRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeUnitvyRepository_2()) as _i4.UnitvyRepository);
  @override
  _i6.Future<_i5.Either<_i8.Failure, List<_i9.Unitvy>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i5.Either<_i8.Failure, List<_i9.Unitvy>>>.value(
              _FakeEither_3<_i8.Failure, List<_i9.Unitvy>>())) as _i6
          .Future<_i5.Either<_i8.Failure, List<_i9.Unitvy>>>);
}
